import test from "ava"
import { AvlTree } from "../src/avl-tree"

test("should return the size of the tree", function(t) {
  var tree = new AvlTree<number, number>()
  t.is(tree.size(), 0)
  tree.insert(1, 1)
  t.is(tree.size(), 1)
  tree.insert(2, 1)
  t.is(tree.size(), 2)
  tree.insert(3, 1)
  t.is(tree.size(), 3)
  tree.insert(4, 1)
  t.is(tree.size(), 4)
  tree.insert(5, 1)
  t.is(tree.size(), 5)
  tree.insert(6, 1)
  t.is(tree.size(), 6)
  tree.insert(7, 1)
  t.is(tree.size(), 7)
  tree.insert(8, 1)
  t.is(tree.size(), 8)
  tree.insert(9, 1)
  t.is(tree.size(), 9)
  tree.insert(10, 1)
  t.is(tree.size(), 10)
})
